# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UseNode@1
  inputs:
    versionSpec: 14.x
    checkLatest: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'build'  # Replace with the path to your built artifacts
    artifactName: 'drop'
