
# FROM mcr.microsoft.com/windows/servercore/iis
# RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*
# COPY . /inetpub/wwwroot/


FROM nginx:alpine
COPY ./html2 /usr/share/nginx/html