name: "[main] CI/CD"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CI Step
        shell: bash
        run: "echo skipping ci/cd until variables are present"

      - name: Declare Variables
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }} # Best practice is to use ${{ secrets. }}
          password: ${{ secrets.DH_PASSWORD }} # Best practice is to use ${{ secrets. }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          file: ./html2/Dockerfile
          push: true
          tags: dhawalthakkar/empid:${{ steps.vars.outputs.sha_short }},dhawalthakkar/empid:latest

      - name: Update Kubernetes Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: -n emptest set image deployment/emptest admin=dhawalthakkar/empid:${{ steps.vars.outputs.sha_short }}
